version: '3'
services:
  cake:
    image: cake:latest
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
#    deploy:
#      replicas: 3
    environment:
      - "HOSTNAME_BOOTSTRAP=cake_cake"
    expose:
      - 4567
    ports:
      - 4567